---
- name: Deploy mezzanine
  hosts: debian-lab

  vars:
    user: "{{ ansible_user }}"
    proj_app: 'mezzanine_exemple'
    proj_name: "{{ proj_app }}"
    venv_home: "{{ ansible_env.HOME }}/.virtualenvs"
    venv_path: "{{ venv_home }}/{{ proj_name }}"
    proj_path: "{{ ansible_env.HOME }}/mezzanine/{{ proj_name }}"
    settings_path: "{{ proj_path }}/{{ proj_name }}"
    reqs_path: '~/requirements.txt'
    manage: "{{ python }}{{ proj_path }}/manage.py"
    live_hostname: 192.168.122.42.nip.io
    domains:
      - 192.168.122.42.nip.io
      - www.192.168.122.42.nip.io
    # repo_url: 'git@github.com:ansiblebook/mezzanine_exemple.git'
    repo_url: 'https://github.com/ansiblebook/mezzanine_exemple.git'
    locale: 'en_US.UTF-8'
    conf_path: /etc/nginx/conf
    tls_enabled: true
    python: "{{ venv_path }}/bin/python3"
    database_name: "{{ proj_name }}"
    database_user: "{{ proj_name }}"
    database_host: localhost
    database_port: 5432
    gunicorn_procname: gunicorn_mezzanine

  vars_files:
    - secrets.yml

  tasks:
    - name: Install apt packages
      become: true
      become_user: root
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        pkg:
          - acl
          - git
          - libjpeg-dev
          - libpq-dev
          - memcached
          - nginx
          - postgresql
          - python3-dev
          - python3-pip
          - python3-venv
          - python3-psycopg2
          - supervisor

    - name: Create project path
      ansible.builtin.file:
        path: "{{ proj_path }}"
        state: directory
        mode: '0755'

    - name: Create a logs directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/logs"
        state: directory
        mode: '0755'

    - name: Download mezzanine_exemple archive
      ansible.builtin.get_url:
        url: >
          https://github.com/ansiblebook/mezzanine_example/archive/refs/heads/master.tar.gz
        dest: /tmp/mezzanine_example.tar.gz
        mode: '0644'

    - name: Extract mezzanine_example archive
      ansible.builtin.unarchive:
        src: /tmp/mezzanine_example.tar.gz
        dest: "{{ proj_path }}"
        remote_src: true
        extra_opts: [--strip-components=1]

    - name: Create python3 virtualenv
      ansible.builtin.pip:
        name:
          - pip
          - wheel
          - setuptools
        state: present
        virtualenv: "{{ venv_path }}"
        virtualenv_command: /usr/bin/python3 -m venv

    - name: Copy requirements.txt to home directory
      ansible.builtin.copy:
        src: requirements.txt
        dest: "{{ reqs_path }}"
        mode: '0644'

    - name: Install packages listed in requirements.txt
      ansible.builtin.pip:
        virtualenv: "{{ venv_path }}"
        requirements: "{{ reqs_path }}"

    - name: Create project locale
      become: true
      community.general.locale_gen:
        name: "{{ locale }}"

    - name: Create a DB user
      become: true
      become_user: postgres
      community.postgresql.postgresql_user:
        name: "{{ database_user }}"
        password: "{{ db_pass }}"

    - name: Create the database
      become: true
      become_user: postgres
      community.postgresql.postgresql_db:
        name: "{{ database_name }}"
        owner: "{{ database_user }}"
        encoding: UTF8
        lc_ctype: "{{ locale }}"
        lc_collate: "{{ locale }}"
        template: template0

    - name: Ensure config path exists
      become: true
      ansible.builtin.file:
        path: "{{ conf_path }}"
        state: directory
        mode: '0755'

    - name: Create tls certificates
      become: true
      ansible.builtin.command: >
        openssl req -new -x509 -nodes -out {{ proj_name }}.crt
        -keyout {{ proj_name }}.key -subj '/CN={{ domains[0] }}' -days 365
      args:
        chdir: "{{ conf_path }}"
        creates: "{{ conf_path }}/{{ proj_name }}.crt"
      when: tls_enabled
      notify: Restart nginx

    - name: Remove the default nginx config file
      become: true
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart nginx

    - name: Set the nginx config file
      become: true
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/mezzanine.conf
        mode: '0640'
      notify: Restart nginx

    - name: Enable the nginx config file
      become: true
      ansible.builtin.file:
        src: /etc/nginx/sites-available/mezzanine.conf
        dest: /etc/nginx/site-enabled/mezzanine.conf
        state: link
      notify: Restart nginx

    - name: Set the supervisor config file
      become: true
      ansible.builtin.template:
        src: templates/supervisor.conf.j2
        dest: /etc/supervisor/conf.d/mezzanine.conf
        mode: '0640'
      notify: Restart supervisor

    - name: Install poll twitter cron job
      ansible.builtin.cron:
        name: "poll twitter"
        minute: "*/5"
        user: "{{ user }}"
        job: "{{ manage }} poll_twitter"

    - name: Set the gunicorn config file
      ansible.builtin.template:
        src: templates/gunicorn.conf.py.j2
        dest: "{{ proj_path }}/gunicorn.conf.py"
        mode: '0750'

    - name: Generate the settings file
      ansible.builtin.template:
        src: templates/local_settings.py.j2
        dest: "{{ settings_path }}/local_settings.py"
        mode: '0750'

    - name: Apply migrations to create the database, collect static content
      community.general.django_manage:
        command: "{{ item }}"
        app_path: "{{ proj_path }}"
        virtualenv: "{{ venv_path }}"
      with_items:
        - migrate
        - collectstatic

    - name: Set the site id
      ansible.builtin.script: scripts/setsite.py
      environment:
        PATH: "{{ venv_path }}/bin"
        PROJECT_DIR: "{{ proj_path }}"
        PROJECT_APP: "{{ proj_app }}"
        DJANGO_SETTINGS_MODULE: "{{ proj_app }}.settings"
        WEBSITE_DOMAIN: "{{ live_hostname }}"
...
